name: crop_yield
description: "Crop yield"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  url_strategy: ^0.3.0
  cached_network_image: ^3.4.0
  fluttertoast: ^8.2.5
  intl: ^0.19.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.1
  sqflite: ^2.3.3+1
  file_picker: ^8.0.7
  path: ^1.8.3
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - fonts/
    - icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 800
        - asset: fonts/Montserrat-Medium.ttf
          weight: 700
        - asset: fonts/Montserrat-Regular.ttf
          weight: 600